# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Empaqueta con tox

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_artifact:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Package with tox
      run: |
        tox
    - name: Move package
      run: |
        mkdir $GITHUB_WORKSPACE/paquete
        cp $GITHUB_WORKSPACE/.tox/.pkg/dist/*.tar.gz $GITHUB_WORKSPACE/paquete/
        ls $GITHUB_WORKSPACE/paquete/
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: assets-for-download
        path: paquete
